travis:
  secure:
    BINSTAR_TOKEN: rTu65cPgajnRc/xmH/2+f+GTKZxCuMgu4HLOvgg+ToGZg/gwG2uMvTYYdJk9Eg94MFAQwqVDHYtUr8ypTrJtQ4JMLIIKm8Z5eaOguuM2Ova6yCoiPeJmZNgpfZPf3vAo4lY4sMJzkwK5yw3OB1uYxVsmkcZNTv/1+fgniGE3yCc+GxwMWOk+/YA3Ru+AExICvYsxuINSe9mcXrdZB9KahidqU8sT7Zw2s7NqIfxWX/pyNOVoqdfCjLkjVTfS1fUNwlL3cpXGYlZvI+e6XJVQVdppUBk7A0a5pcgyiuDggIwQFidwDffJ5HnPNYbRplOghUYXa0iMhzSrLGjbDXaxXALkIMotusGlx3hedzBUsqJ5kFfQ8ZwReRFQGBtbXp1abueYMRgKN06ZGAwHbNzaA7SYdrNXsZ02GMJ+q114DURMvpJlxRRFyhrliENgjXujUX6kskabF3S9FZlj6LGun29N2aiAren0fTczDlDioK2kJqi1ZMOKKQe1EsKX0B6E0nH0b4pBCF7CsTJmqx5HYPBI4nF6D2Xwo/AQkbwfyiv4ZUFacchmnUD38Du8M3y++PLxcqz82dqb1CXOC3JqgP6fzVGguiAillCDUJhrKU2XZEbomH8A+rthl17naYiF1SWXK12N/s7VhJF3y0qfZ+ErUK+ftUFfmRev9uup0ks=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
